name: blue_eye
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  smooth_star_rating:
  tflite:
  image_picker:
  camera:
  dialog_flowtter:
  tflite_audio:
  readmore:
  eva_icons_flutter:
  font_awesome_flutter:
  flutter_tts:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/emotion_detection_by_image/
    - assets/emotion_detection_by_voice/
    - assets/emotion_detection_by_pose/
    - assets/object_detection/
    - assets/dialog_flow_auth.json
    - assets/image/